### ISSUE TITLE
Suggestion: show which statements were already curated

### ISSUE THREAD

**Issue by cthoyt** [indralab/emmaa#140]
Would be nice to see which statements were already curated, since it's already showing a nice icon that there are edits. Maybe use color (stoplight analogy - green for agree, red for some wrong annotations, yellow for medium badness annotations)

<img width="1062" alt="Screen Shot 2020-04-22 at 00 08 47" src="https://user-images.githubusercontent.com/5069736/79918852-89e36f80-842d-11ea-95c3-15847f322566.png">

Source of screenshot: https://emmaa.indra.bio/all_statements/covid19/?sort_by=evidence&page=1&filter_curated=false (the EMMAA model for covid19)

In terms of style, it would look better if there were a little bit of margin around those badges too

**Comment by bgyori** [comment]
I agree - on some of the other views, green and red are differentiated to show correct vs incorrect curations at the statement level, and there are yet other views of statements where the evidence-level pencil indicates correct or incorrect existing curations. We'll discuss how to expose those on this page as well.

**Comment by bgyori** [comment]
I think curations are now shown in all the different views so closing this.
